name: expense_tracker
description: A command-line expense tracking application.
version: 1.0.0


environment:
  sdk: ^3.4.4


dependencies:
  riverpod: ^2.5.4
  json_annotation: ^4.4.0
  uuid: ^3.0.6


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
